### ISSUE TITLE
Installation test bug: TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by deanputney** [algorithmic-music-exploration/amen#88] opened 2017-04-02 00:15 UTC
When running the installation test script as described on the README I get this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/amen/synthesize.py", line 100, in synthesize
    truncated_array = sparse_array[:, 0:max_samples].toarray()
  File "/Library/Python/2.7/site-packages/scipy/sparse/lil.py", line 289, in __getitem__
    return self._get_row_ranges(i, j)
  File "/Library/Python/2.7/site-packages/scipy/sparse/lil.py", line 320, in _get_row_ranges
    j_start, j_stop, j_stride = col_slice.indices(self.shape[1])
TypeError: only integer scalar arrays can be converted to a scalar index
```

I was able to trace this down to the `max_samples` array not being parsed properly to an array index when used in `sparse_array[:, 0:max_samples].toarray()`. I was able to fix the issue on my local system by changing this to `sparse_array[:, 0:max_samples[0]].toarray()`.

Not sure if this is an error associated with my installation or with the code here. This is a fresh install of Anaconda on Python 2.7.

**Comment by tkell** [comment] 2017-04-02 17:43
Cheers Dean - thanks for the find & glad you got it fixed.  We'll take a look at this soon.

**Comment by tkell** [comment] 2017-05-07 17:47
Ahh, looks like this is caused by using librosa 0.5.  Got a fix locally, will push soon.  Many thanks!

**Comment by tkell** [comment] 2017-05-07 18:25
Fixed with https://github.com/algorithmic-music-exploration/amen/pull/90

**Closed by tkell** 2017-05-07 18:25 UTC
